# Generated by Django 3.2.18 on 2023-04-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty_user_end', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiry_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
