# Generated by Django 3.2.18 on 2023-05-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty_user_end', '0002_alter_product_expiry_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
