# Generated by Django 3.2.18 on 2023-05-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty_user_end', '0003_auto_20230501_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_id',
            new_name='id',
        ),
    ]
